steps:
# Run tests before building
- name: 'python:3.13-slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      cd ${_SERVICE}
      # Install uv for fast dependency management
      pip install uv
      # Install dependencies and run tests
      uv sync
      uv run pytest --junitxml=test-results.xml --cov=src
  id: 'run-tests'
  waitFor: ['-']

# Build the Docker image (only if tests pass)
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE}', '-f', '${_SERVICE}/Dockerfile', '.']
  id: 'docker-build'
  waitFor: ['run-tests']

# Push the Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE}']
  id: 'docker-push'
  waitFor: ['docker-build']

# Optional: Deploy with gcloud run (keeping for backward compatibility)
# This step will be skipped if _SKIP_GCLOUD_DEPLOY is set to 'true'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  secretEnv: ['GEMINI_API_KEY']
  entrypoint: bash
  args:
    - '-c'
    - |
      # All services need these common flags. Use --update-env-vars for all.
      common_flags="--image=${_IMAGE} \
        --max-instances=${_MAX_INSTANCES} \
        --region=${_REGION} \
        --platform=managed \
        --service-account=${_APP}-${_SERVICE}-user@${PROJECT_ID}.iam.gserviceaccount.com \
        --no-allow-unauthenticated \
        --ingress=internal"
      
      # Conditionally add the GEMINI_API_KEY and MCP_SERVER_URL_GCP for the 'chat' service only
      if [ "${_SERVICE}" == "${_CHAT_SERVICE}" ]; then
        echo "Adding GEMINI_API_KEY and MCP_SERVER_URL_GCP to the chat service environment variables."
        common_flags+=" --update-env-vars=GEMINI_API_KEY=$$GEMINI_API_KEY,MCP_SERVER_URL_GCP=https://${_APP}-${_MCP_SERVER}-${PROJECT_NUMBER}.${_REGION}.run.app"
      fi
      
      # Conditionally add the CHAT_API_URL for the 'dashboard' service only
      if [ "${_SERVICE}" == "${_DASHBOARD_SERVICE}" ]; then
        echo "Adding CHAT_API_URL to the dashboard service environment variables."
        common_flags+=" --update-env-vars=CHAT_API_URL=https://${_APP}-${_CHAT_SERVICE}-${PROJECT_NUMBER}.${_REGION}.run.app"
      fi

      # Deploy based on IAP variable
      if [ "${_IAP}" == "true" ]; then
        # IAP requires gcloud beta and specific flags
        echo "Deploying with IAP..."
        gcloud beta run deploy ${_APP}-${_SERVICE} $common_flags \
          --iap
      else
        # Standard deployment without IAP
        echo "Deploying without IAP..."
        gcloud run deploy ${_APP}-${_SERVICE} $common_flags
      fi
  id: 'gcloud-deploy'
  waitFor: ['docker-push']

images:
- '${_IMAGE}'

substitutions:
  _REGION: 'europe-west4'
  _IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP}/${_SERVICE}:${SHORT_SHA}'
  _APP: 'sbotify'
  _MCP_SERVER: 'mcp-server'
  _CHAT_SERVICE: 'chat'
  _DASHBOARD_SERVICE: 'dashboard'
  _MAX_INSTANCES: '1'
  _SERVICE: ''
  _IAP: 'false'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/GEMINI_API_KEY/versions/latest
    env: 'GEMINI_API_KEY'