steps:
# Build and push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE}', 'src/${_SERVICE}']

# Deploy the image to Cloud Run
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_IMAGE}']

# Deploy the image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - ${_APP}-${_SERVICE}
  - --image
  - '${_IMAGE}'
  - --region
  - '${_REGION}'

images:
- '${_IMAGE}'

substitutions:
  _REGION: 'europe-west4'
  _IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_APP}/${_SERVICE}:${SHORT_SHA}'
  _APP: 'sbotify'

options:
  logging: CLOUD_LOGGING_ONLY