services:
  mcp-server:
    build:
      context: .
      dockerfile: ./mcp-server/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
    networks:
      - sbotify-network

  chat:
    build:
      context: .
      dockerfile: ./chat/Dockerfile
      # args:
      #   SERVICE_DIR: chat
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - MCP_SERVER_URL=http://mcp-server:8080/mcp
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mcp-server
      # mcp-server:
      #   condition: service_healthy
    networks:
      - sbotify-network

  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
      args:
        SERVICE_DIR: dashboard
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CHAT_API_URL=http://chat:8080
    depends_on:
      - chat
    networks:
      - sbotify-network

networks:
  sbotify-network:
    driver: bridge