steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/mcp-server:${SHORT_SHA}', 'mcp-server']
images:
- 'gcr.io/${PROJECT_ID}/mcp-server:${SHORT_SHA}'
options:
  logging: CLOUD_LOGGING_ONLY