steps:
# Step 1: Build and push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/${PROJECT_ID}/sbotify/mcp-server:${SHORT_SHA}', 'mcp-server']

# Step 2: Deploy the image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - sbotify-mcp-server 
  - --image
  - 'europe-west4-docker.pkg.dev/${PROJECT_ID}/sbotify/mcp-server:${SHORT_SHA}'
  - --region
  - europe-west4

images:
- 'europe-west4-docker.pkg.dev/${PROJECT_ID}/sbotify/mcp-server:${SHORT_SHA}'

substitutions:
  _IMAGE_NAME: 'mcp-server:${SHORT_SHA}'
  _AR_REPO_URL: 'europe-west4-docker.pkg.dev/${PROJECT_ID}/sbotify'

options:
  logging: CLOUD_LOGGING_ONLY