steps:
# Step 1: Build and push the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMAGE_NAME', 'mcp-server']
  
# Step 2: Deploy the image to Cloud Run
- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
  args:
  - gcloud
  - run
  - deploy
  - sbotyif-mcp-server 
  - --image
  - '$_IMAGE_NAME'
  - --region
  - europe-west4
  - --allow-unauthenticated

images:
- '$_IMAGE_NAME'

# The 'substitutions' block goes here at the top level
substitutions:
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/mcp-server:${SHORT_SHA}'

options:
  # The 'options' block is for things like logging
  logging: CLOUD_LOGGING_ONLY