steps:
  # This step builds the mcp-server image.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA'
      - '-f'
      - './Dockerfile'  # The Dockerfile path is now relative to the current directory
      - '.'  # The build context is now the mcp-server directory
    id: 'build-mcp-server'

  # This step pushes the mcp-server image to Google Container Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA'
    id: 'push-mcp-server'
    waitFor: ['build-mcp-server']

# The `images` field lists the container images to be pushed after the build is complete.
images:
  - 'gcr.io/$PROJECT_ID/mcp-server:$COMMIT_SHA'

# The `options` field contains global options for the build.
options:
  logging: CLOUD_LOGGING_ONLY