[project]
name = "mcp-server"
version = "0.1.0"
dependencies = [
    "fastmcp",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-mock",
    "pytest-asyncio"
]

[tool.pytest.ini_options]
pythonpath = ["."]
