name: Chat CI/CD

on:
  pull_request:
    paths:
      - "chat/**"
      - ".github/workflows/chat-ci-cd.yml"
  push:
    branches: ['*']
    paths:
      - "chat/**"
      - ".github/workflows/chat-ci-cd.yml"

jobs:
  debug-output:
    needs: check-changes
    runs-on: ubuntu-latest
    steps:
      - name: Print folder-changed
        run: echo "folder-changed = ${{ needs.check-changes.outputs.folder-changed }}"
  check-changes:
    uses: ./.github/workflows/check-changes.yml
    with:
      folder: chat

  call-base:
    needs: check-changes
    if: needs.check-changes.outputs.folder-changed == 'true'
    uses: ./.github/workflows/workflow-base.yml
    with:
      service: chat
      dockerfile: chat/Dockerfile
      folder: chat
