name: Render PlantUML Diagrams

on:
  push:
    paths:
      - '**/*.puml' # Trigger when any .puml file is pushed

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          args: -tsvg -o diagrams/ **/*.puml
          # -tsvg specifies SVG output
          # -o diagrams/ specifies the output directory
          # **/*.puml tells it to find all .puml files in the repo
          
      - name: Commit rendered diagrams
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🎨 Rendered new PlantUML diagrams'
          file_pattern: 'diagrams/*.svg'