name: Render PlantUML Diagrams

on:
  push:
    branches:
      - dashboard

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render PlantUML Diagrams
        uses: holowinski/plantuml-github-action@1.2021.1
        with:
          args: -tsvg -o diagrams/ **/*.puml

      - name: Commit rendered diagrams
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🎨 Rendered PlantUML diagrams'
          file_pattern: 'diagrams/*.svg'