name: Tests

on:
  workflow_call:
    inputs:
      folder:
        required: true
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install uv
        run: pip install uv
      - name: Run tests
        run: |
          cd ${{ inputs.folder }}
          uv venv --seed
          source .venv/bin/activate
          uv sync
          uv run pytest --verbose --tb=short
